2 tests DataSourcePatterns class
bridgedb/BridgeDb pull request #237
Opened 2024-02-28 16:49 UTC by youphendriks

Valid input working, invalid input Disabled cause I have to figure out how to throws.
getDataSourceMatches class does not throw an exception on following inputs; "", " "
Is there a different method to make my test throw an exception or is the problem the lack of exception handling in the codebase?

2024-02-29 18:59 UTC, egonw commented on org.bridgedb/src/test/java/org/bridgedb/DataSourcePatternsTest.java
> + *Copyright (c) 2012 OpenPhacts
I don't think there is any code left from the previous session. Please update this line to just list your name. If you do prefer not to give your email address, you can use `<youphendriks@github.com>`, but likely your email address is in the git commit message anyway.

2024-02-29 19:00 UTC, egonw commented on org.bridgedb/src/test/java/org/bridgedb/DataSourcePatternsTest.java
> + * Tests the {@link org.bridgedb.DataSourcePatterns} class
The first sentence of JavaDoc should always end with a period. Please add these.

2024-02-29 19:00 UTC, egonw requested changes
See my comments.

2024-02-29 19:02 UTC, egonw commented
> Is there a different method to make my test throw an exception or is the problem the lack of exception handling in the codebase?

I need a bit more explanation here, because I am not sure what you mean.

2024-03-01 09:28 UTC, youphendriks commented
Implemented changes: added "." to JavaDoc and changed name and email to mine. I believe this commit has been added to the PR, could you check?

2024-03-04 05:38 UTC, egonw approved these changes

2024-03-04 05:38 UTC, merged

2024-03-04 05:40 UTC, egonw commented
Thanks, merged! I updated the copyright year (since you write it this year) and some formatting. We should have a template for the copyright/license header and then apply it to all files. Right now, many still are a mix of copyright/license and documentation (the last should be in the JavaDoc instead, in my opinion).

2024-03-04 05:47 UTC, youphendriks commented
Good to know I should also update the copyright year, I was not sure if I should do this.
I’ll set up a template and start making it uniform.
Today I will work on implementing mockito, I’ll keep you posted!
________________________________
From: Egon Willighagen ***@***.***>
Sent: Monday, March 4, 2024 6:41:02 AM
To: bridgedb/BridgeDb ***@***.***>
Cc: Youp Hendriks ***@***.***>; Author ***@***.***>
Subject: Re: [bridgedb/BridgeDb] 2 tests DataSourcePatterns class (PR #237)


Thanks, merged! I updated the copyright year (since you write it this year) and some formatting. We should have a template for the copyright/license header and then apply it to all files. Right now, many still are a mix of copyright/license and documentation (the last should be in the JavaDoc instead, in my opinion).

—
Reply to this email directly, view it on GitHub<https://github.com/bridgedb/BridgeDb/pull/237#issuecomment-1975771581>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AK7FBZFRY57HCHILLM6C4S3YWQCO5AVCNFSM6AAAAABD6MDSYSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNZVG43TCNJYGE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>